public enum Commands {
    ADD_LOCO, EXIT, ADD_PASWAG, SHOW_TRAIN, CLOSE_TRAIN, START, SIMULATION,LOAD_PASWAG, RM_TRAIN, CLIMA, KICK,
    ADD_MAIL, LOAD_MAIL, GUARD, BURN, ADD_BAM, STEAL, SORT_BAM, ADD_DIN, ORDER_FOOD, ADD_BFW, LOAD_BFW, ADD_HBFW,
    LOAD_HBFW, ADD_FRIDGE, LOWER_TEMP, CHECK_TEMP, ADD_LIQUID, SABOTAGE, FILL_LIQUID, ADD_GAS, FILL_GAS, CHECK_PRESS,
    ADD_EXPL, LOAD_EXPL, DRINK, ADD_TOXIC, EX, LOAD_TOXIC, ADD_LTOXIC, LOAD_LTOXIC;
}
