public class Stations {
    private static String[] stations = {
            "Augustów",
            "Białystok",
            "Bielsko-Biała",
            "Bydgoszcz",
            "Bytom",
            "Chełm",
            "Chorzów",
            "Częstochowa",
            "Dąbrowa Górnicza",
            "Elbląg",
            "Gdańsk",
            "Gdynia",
            "Gliwice",
            "Gorzów Wielkopolski",
            "Grudziądz",
            "Inowrocław",
            "Jastrzębie-Zdrój",
            "Jaworzno",
            "Jelenia Góra",
            "Kalisz",
            "Katowice",
            "Kędzierzyn-Koźle",
            "Kielce",
            "Konin",
            "Koszalin",
            "Kraków",
            "Krosno",
            "Kutno",
            "Legnica",
            "Leszno",
            "Łódź",
            "Lubin",
            "Lublin",
            "Mielec",
            "Mikołów",
            "Mława",
            "Nowa Sól",
            "Nowy Sącz",
            "Olsztyn",
            "Opole",
            "Ostrołęka",
            "Ostrowiec Świętokrzyski",
            "Pabianice",
            "Piotrków Trybunalski",
            "Płock",
            "Poznań",
            "Pruszcz Gdański",
            "Przemyśl",
            "Radom",
            "Ruda Śląska",
            "Rybnik",
            "Rzeszów",
            "Sandomierz",
            "Sanok",
            "Siedlce",
            "Sieradz",
            "Skierniewice",
            "Słupsk",
            "Sochaczew",
            "Sopot",
            "Starachowice",
            "Stargard Szczeciński",
            "Suwałki",
            "Świdnica",
            "Świebodzin",
            "Świecie",
            "Tarnobrzeg",
            "Tarnów",
            "Tczew",
            "Tomaszów Mazowiecki",
            "Toruń",
            "Trzebinia",
            "Tychy",
            "Ustroń",
            "Wałbrzych",
            "Warszawa",
            "Wejherowo",
            "Włocławek",
            "Wodzisław Śląski",
            "Wrocław",
            "Zabrze",
            "Zakopane",
            "Zamość",
            "Zduńska Wola",
            "Zielona Góra",
            "Złotów",
            "Złotoryja",
            "Żary",
            "Żnin",
            "Żory",
            "Żyrardów",
            "Żywiec",
            "Chojnice",
            "Dębica",
            "Giżycko",
            "Jarosław",
            "Krosno Odrzańskie",
            "Mińsk Mazowiecki",
            "Prudnik",
            "Szczucin"
    };

    public static String[] getStations() {
        return stations;
    }
}
